https://realpython.com/numpy-array-programming/

In [1]:
import numpy as np

In [2]:
np.random.seed(444)
x = np.random.choice([True, False], size=10000)
x

array([False,  True, False, ..., False,  True, False])

In [3]:
np.arange(10)[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.arange(10)[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
def count_transition(x) -> int:
    count = 0
    for i, j in zip(x[:-1], x[1:]):
        if j and not i:
            count += 1
    return count

In [6]:
count_transition(x)

2511

In [7]:
np.count_nonzero(x[:-1] < x[1:])

2511

In [8]:
from timeit import timeit
setup = 'from __main__ import count_transition, x; import numpy as np'
num = 1000
t1 = timeit('count_transition(x)', setup=setup, number=num)
t2 = timeit('np.count_nonzero(x[:-1] < x[1:])', setup=setup, number=num)
print('Speed difference: {:0.1f}x'.format(t1 / t2))

Speed difference: 51.9x


## flatten

In [9]:
a = np.array([[1,2], [3,4]])
print(a.shape)
print(a.flatten())
print(a.flatten().shape)
print(np.array([1,2,3,4]).shape)
print(np.array([[1],[2],[3],[4]]).shape)

(2, 2)
[1 2 3 4]
(4,)
(4,)
(4, 1)


## vectorize

In [10]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b

In [11]:
vfunc = np.vectorize(myfunc)

In [12]:
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

In [13]:
vfunc(np.array([[1,2], [3,4]]), 2)

array([[3, 4],
       [1, 2]])

In [14]:
def unary_func(a):
    return 2*a
vfunc2 = np.vectorize(unary_func)
vfunc2([1, 2, 3, 4])

array([2, 4, 6, 8])

## broadcasting

In [15]:
a = np.array([1.5 , 2.5, 3.5])
b = np.array([10., 5., 1.])
a/b

array([0.15, 0.5 , 3.5 ])

In [16]:
sample = np.random.normal(loc=[2., 20.], scale=[1., 3.5], size=(3, 2))
sample

array([[ 0.28894178, 19.36923767],
       [ 2.22249248, 17.85200908],
       [ 2.65525941, 17.78955748]])

In [17]:
mu = sample.mean(axis=0) # column-wise means
mu

array([ 1.72223122, 18.33693474])

In [18]:
print(sample.shape, mu.shape)

(3, 2) (2,)


In [19]:
#z-score
(sample - sample.mean(axis=0)) / sample.std(axis=0)

array([[-1.39320284,  1.4133517 ],
       [ 0.48626982, -0.66392383],
       [ 0.90693302, -0.74942787]])

In [20]:
sample.min(axis=1)

array([0.28894178, 2.22249248, 2.65525941])

In [21]:
sample.min(axis=1).reshape((3,1))

array([[0.28894178],
       [2.22249248],
       [2.65525941]])

In [22]:
sample.min(axis=1)[:, None]

array([[0.28894178],
       [2.22249248],
       [2.65525941]])