https://realpython.com/numpy-array-programming/

In [17]:
import numpy as np

In [18]:
np.random.seed(444)
x = np.random.choice([True, False], size=10000)
x

array([False,  True, False, ..., False,  True, False])

In [19]:
np.arange(10)[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.arange(10)[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
def count_transition(x) -> int:
    count = 0
    for i, j in zip(x[:-1], x[1:]):
        if j and not i:
            count += 1
    return count

In [22]:
count_transition(x)

2511

In [23]:
np.count_nonzero(x[:-1] < x[1:])

2511

In [24]:
from timeit import timeit
setup = 'from __main__ import count_transition, x; import numpy as np'
num = 1000
t1 = timeit('count_transition(x)', setup=setup, number=num)
t2 = timeit('np.count_nonzero(x[:-1] < x[1:])', setup=setup, number=num)
print('Speed difference: {:0.1f}x'.format(t1 / t2))

Speed difference: 47.7x


## flatten

In [30]:
a = np.array([[1,2], [3,4]])
print(a.shape)
print(a.flatten())
print(a.flatten().shape)
print(np.array([1,2,3,4]).shape)
print(np.array([[1],[2],[3],[4]]).shape)

(2, 2)
[1 2 3 4]
(4,)
(4,)
(4, 1)


## vectorize

In [31]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b

In [35]:
vfunc = np.vectorize(myfunc)

In [36]:
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

In [37]:
vfunc(np.array([[1,2], [3,4]]), 2)

array([[3, 4],
       [1, 2]])

In [39]:
def unary_func(a):
    return 2*a
vfunc2 = np.vectorize(unary_func)
vfunc2([1, 2, 3, 4])

array([2, 4, 6, 8])

## broadcasting

In [40]:
a = np.array([1.5 , 2.5, 3.5])
b = np.array([10., 5., 1.])
a/b

array([0.15, 0.5 , 3.5 ])

In [43]:
sample = np.random.normal(loc=[2., 20.], scale=[1., 3.5], size=(3, 2))
sample

array([[ 2.1478319 , 17.29435724],
       [ 1.02018156, 23.13203027],
       [ 1.63909082, 18.17705259]])

In [45]:
mu = sample.mean(axis=0) # column-wise means
mu

array([ 1.60236809, 19.53448003])

In [46]:
print(sample.shape, mu.shape)

(3, 2) (2,)


In [47]:
#z-score
(sample - sample.mean(axis=0)) / sample.std(axis=0)

array([[ 1.18297982, -0.87189776],
       [-1.26262258,  1.40023396],
       [ 0.07964276, -0.5283362 ]])

In [48]:
sample.min(axis=1)

array([2.1478319 , 1.02018156, 1.63909082])

In [56]:
sample.min(axis=1).reshape((3,1))

array([[2.1478319 ],
       [1.02018156],
       [1.63909082]])

In [57]:
sample.min(axis=1)[:, None]

array([[2.1478319 ],
       [1.02018156],
       [1.63909082]])